### ISSUE TITLE
Project - Add more images

### ISSUE THREAD

**Issue by dud3** [Drooids/drooids.github.io#14]
Add more images per `each project`.

How would we want to see them appear:

a.) Simply list more images in a manner that they would make sense for each project, such as: if we define project 0 as `p0`, project 1 as `p1` and so forth...  then we would have `p0i0`(i stands for image, `i0` image 0), `p0i1`... Summary don't throw images randomly.

b.) Main image -> click -> have modal with all images

c.) I'm not sure, you might want to come up with something.

**Comment by dud32** [comment]
Done.
