### ISSUE TITLE
Core - Contact form

### ISSUE THREAD

**Issue by dud3** [Drooids/drooids.github.io#6]
Make the `contact form actually work`.
## Note

Use pure js and probably `mandrill`.

**Comment by dud32** [comment]
It says on the form:
To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19.
The form should work on most web servers, but if the form is not working you may need to configure your web server differently.

**Comment by dud3** [comment]
Place this inside: `drooids.js`:

``` js
$('#id-of-submit-button').click(function(){

  var xhr = $.ajax({
    type: 'POST',
    url: "https://mandrillapp.com/api/1.0/messages/send.json",
    dataType: 'json',
    data: {
      key: 'h7nP27VyRFNZ8MTSaqmW6g',
      message: {
        text: "Example text content",
        subject: "example subject",
        from_email: "mail@example.com",
        from_name: "Example Name",
        to: [{
          "email": "mail@example.com",
          "name": "Recipient Name"
        }]
      }
    }
  });

  xhr.done(function(data) {
    // show the success message
  });

  xhr.fail(function(jqXHR, textStatus, errorThrown) {
    // Please try again
  });

});
```

**Comment by dud32** [comment]
I get this error:

XMLHttpRequest cannot load file:///home/sigd/git/pro/drooids/
drooids.github.io/mail/contact_me.php. Cross origin requests are only
supported for protocol schemes: http, data, chrome, chrome-extension,
https, chrome-extension-resource.
