### ISSUE TITLE
General - Location

### ISSUE THREAD

**Issue by dud3** [Drooids/drooids.github.io#8]
Have a link to the map of the `Location` section.
## Note

Only load the script when required and NOT on page load.

**Comment by dud3** [comment]
@dud32 +review.

**Comment by dud3** [comment]
@dud32 +implement.

**Comment by dud3** [comment]
@dud32 +implement.

**Comment by dud32** [comment]
What do you mean?

**Comment by dud3** [comment]
Chose one: https://snazzymaps.com/explore?color=gray
